erupt-app:
  # 로그인이 실패 카운트. 인증 코드가 필요합니다.
  verifyCodeCount: 5
  # 워터마크 활성화 여부
  water-mark: false
erupt:
  # CSRF 방어 활성화 여부
  csrfInspect: true
  # 세션을 저장하기 위해 redis를 활성화할지 여부, 기본값은 false입니다. 활성화한 후 구성 파일에 redis 구성을 추가해야 합니다(spring boot와 동일).
  redisSession: true
  # 첨부 파일 업로드 저장 경로, 기본 경로는 /opt/erupt-attachment입니다.
  uploadPath: D:/Git/erupt/attachment
  # 업로드한 파일의 원래 이름을 유지할지 여부
  keepUploadFileName: false
  # 로그인 세션 시간(redisSession이 true인 경우 유효함)
  upms.expireTimeByLogin: 60
  # 작업 로그 기록 여부, 기본값은 true이며, 이 기능을 활성화한 후 [시스템 관리 → 작업 로그]에서 작업 로그를 확인할 수 있습니다.
  security.recordOperateLog: true


magic-api:
  web: /magic/web
  # 인터페이스 구성 파일 저장 경로
  resource.location: D:/Git/erupt/magic-script
  show-url: false

spring:
  datasource:
    url: jdbc:mysql://database-1.cosxrbrmnajg.ap-northeast-2.rds.amazonaws.com:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: 1Dhksrl11!
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  profiles:
    active: dev
  mail:
    username: jerry102471@gmail.com
    password: 1Dhksrl11!
    host: smtp.gmail.com
    properties:
      mail.smtp.ssl.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  # gzip 압축 활성화
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS